version: "3.3"
services:

  mongodb:
    container_name: cryptonfts_mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - cryptonfts_mongodb:/data/db
    ports:
      - 27017:27017

  mongo-express:
    container_name: cryptonfts_mongo-express
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    depends_on:
      - mongodb

volumes:
  cryptonfts_mongodb:
    driver: local